import streamlit as st
import openai
from PIL import Image
from io import BytesIO
import requests

# 함수: OpenAI API 호출을 통한 텍스트 응답 생성
@st.cache_data
def get_openai_text_response(api_key, prompt):
    openai.api_key = api_key
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message['content']

# 함수: OpenAI API 호출을 통한 이미지 생성
@st.cache_data
def get_openai_image_response(api_key, prompt):
    openai.api_key = api_key
    response = openai.Image.create(
        prompt=prompt,
        n=1,
        size="512x512"
    )
    image_url = response['data'][0]['url']
    image_response = requests.get(image_url)
    return Image.open(BytesIO(image_response.content))

# 세션 상태 초기화
if 'api_key' not in st.session_state:
    st.session_state.api_key = ''
if 'text_prompt' not in st.session_state:
    st.session_state.text_prompt = ''
if 'image_prompt' not in st.session_state:
    st.session_state.image_prompt = ''

# API Key 입력
st.sidebar.title("Settings")
st.session_state.api_key = st.sidebar.text_input("openai api key를 입력하세요.", type="password", value=st.session_state.api_key)

# 페이지 선택
page = st.sidebar.selectbox("Select a Page", ["채팅하기", "그림생성 ai"])

if page == "채팅하기":
    st.title("채팅하기")
    
    # 질문 입력
    st.session_state.text_prompt = st.text_area("질문 입력:", value=st.session_state.text_prompt)
    
    # 응답 표시
    if st.button("응답얻기"):
        if st.session_state.api_key and st.session_state.text_prompt:
            response = get_openai_text_response(st.session_state.api_key, st.session_state.text_prompt)
            st.text_area("Response:", value=response, height=200)
        else:
            st.error("Please enter both the API Key and a question.")

elif page == "그림생성 ai":
    st.title("그림생성 ai")
    
    # 프롬프트 입력
    st.session_state.image_prompt = st.text_area("그림생성을 위한 프롬프트를 입력하세요:", value=st.session_state.image_prompt)
    
    # 이미지 생성 및 표시
    if st.button("그림 생성"):
        if st.session_state.api_key and st.session_state.image_prompt:
            image = get_openai_image_response(st.session_state.api_key, st.session_state.image_prompt)
            st.image(image, caption="Generated by Dall-E", use_column_width=True)
        else:
            st.error("openai api key를 입력하세요.")
